---
train:

    params:
        batch_size: 20
        epoch: &end_step 10
        lr: 0.0005
        decay: 0.5
        decay_step: 3
        #warmup: 3
        warmup: 0

    save:
        metapath: "/home/rp/datasets/Output/HybirdGaze"
        folder: eth/swin
        model_name: trans6
        step: 5

    data:
        image: "/home/rp/datasets/FaceBased/ETH-Gaze/train"
        label: "/home/rp/datasets/FaceBased/ETH-Gaze/train.label"
        header: True
        name: eth
        isFolder: False

    pretrain:
        enable: False
        path: PLACEHOLDER
        device: PLACEHOLDER

    device: 0

    ave_loss: 1000

    reader: reader

test:

    load:
        begin_step: 10
        end_step: *end_step
        steps: 10

    data:
        image: "/home/rp/datasets/FaceBased/ETH-Gaze/test"
        label: "/home/rp/datasets/FaceBased/ETH-Gaze/test.label"
        name: eth/swin
        header: True
        isFolder: False

    savename: "evaluation"

    device: 0

    reader: reader

# dropout = 0
# dim_feed = 512